@startuml
'object GameState
'object Level
object Static
object Solid
object Marker
object Dynamic
object Interruptable
object Infinite
object Deterministic
object NPC

'GameState o-- Level
'Level o-- Static
Static <|-- Solid
Static <|-- Marker

'GameState o-- Dynamic
Dynamic <|-- Interruptable
Dynamic <|-- Infinite
Dynamic <|-- Deterministic
Dynamic <|-- NPC

@enduml
