@startmindmap
* Intent
** Murphy
*** MurphyTryToMove
*** MurphyTryToSnap
*** InstantMurphyPush
** Continue/Gravity
*** BecomesVoid
*** InstantTriggerVoid
*** MurphyEntered
*** ZonkEntered
*** FloppyOrangeEntered
*** InfotronEntered
** Explosion
*** ExplodeNormal
*** ExplodeInfotron
@endmindmap