@startmindmap
* Intent
** Murphy
*** MurphyTryToMove
*** MurphyTryToSnap
*** InstantMurphyPush
** Continue/Gravity
*** BecomesVoid
*** InstantTriggerVoid
*** MurphyEntered
*** ZonkRolled
*** FloppyOrangeEntered
*** InfotronRolled
** Explosion
*** ExplodeNormal
*** ExplodeInfotron
@endmindmap