@startuml
Display --* Configuration
Configuration --o SDLContext
SDLContext --o GLContext
GLContext --o GameContext
class "Assets\nSprites" as Sprites
class "Assets\nSounds" as Sounds
Configuration --o Sprites
Sprites --o GameContext
Configuration --o Sounds
Sounds --o GameContext
Configuration --o GameContext
GameContext o-- GameState
GameState o-- Level
GameState o-- GameTime
Level o-- Element
@enduml
